/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scene.gltf --transform 
Files: scene.gltf [5.68KB] > /Users/kevinheleodoro/Projects/3D/sad_toaster/scene-transformed.glb [290.99KB] (-5023%)
Author: Tasha.Lime (https://sketchfab.com/tasha.lime)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/sad-toaster-9b158486dfa1490eb9157966321283a0
Title: Sad toaster
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Toaster(props) {
  const { nodes, materials } = useGLTF('/models/toaster-transformed.glb')
  return (
    <group {...props} dispose={null} position={[0, -1.5, 0]} scale={[1.5, 1.5, 1.5]} rotation={[0, 5, 0]}>
      <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials['Material.002']} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/toaster-transformed.glb')
